### ISSUE TITLE
[C4GT Community]: Markdown Rendering and Display

### ISSUE THREAD

**Issue by KDwevedi** [BharatSahAIyak/kg-markdown-enhancer#5]
## Description
Setup functionality to read and update markdown.

## Goals
- [ ] Read markdown for a local config file
- [ ] Setup the ability to render that markdown: [marked-js](https://marked.js.org/)
- [ ] Implement clicking properly as described below

### Expected Outcome

In #4 , we'll setup the ability to read from the DB.

Now, any named entities should be highlighted in the markdown text. For example, in this screenshot from wikipedia:

<img width="648" alt="Screenshot 2024-03-16 at 9 09 47 PM" src="https://github.com/BharatSahAIyak/kg-markdown-enhancer/assets/74085496/6d22e390-0122-48b3-81c8-67de00d1bf48">

The word for `Chicago` is highlighted as a link because there is an article called 'Chicago' in the database.

When such a highlighted word is clicked, it triggers a function that zooms into that node on the graph visualisation. (Implementing this function is part of #4 , this can be a mock function pre-integration.)

### Implementation Details

Original ticket : #1 
[marked-js](https://marked.js.org/) is a renderer that can be leveraged

### Product Name

Bharat Sahaiyak

### Organisation Name

SamagraX

### Tech Skills Needed

HTML, JavaScript

### Mentor(s)

@KDwevedi 

### Complexity

Medium

### Category

Frontend

**Comment by PRANJALRANA11** [comment]
Hy @KDwevedi could i work on this

**Comment by nope3472** [comment]
@KDwevedi, After thoroughly reviewing all the mentioned points, I'm eager to start contributing to the project, especially leveraging my proficient skills in JavaScript. With your guidance, I'm confident I can make meaningful contributions.

**Comment by Singh-Supreet** [comment]
@KDwevedi  I am very confident that I will be able to do this efficiently. I have a lot of experience in making responsive websites. Looking forward to discussing with you

**Comment by Yash-Sajwan24** [comment]
@KDwevedi I understand the problem, and I believe I have the necessary skills. Could I have the opportunity to work on this?

**Comment by aryangandhi05** [comment]
Hare krishna @KDwevedi Sir I want to solve this issue, as i understand it, and i will give my 100% for solving this issue So please can you assign me this?

**Comment by AKSHATkumar22** [comment]
Hello Sir, my name is Akshat Kumar as I have worked and built many projects as a fresher and learner wanted to work on this issue and wanted to resolve the issue. As, I think with my tech skills knowledge I have can add some value to this project and complete the project. So, Sir please let me give a chance to showcase and perform under your guidance.
